# Installing docker engine 
# ubuntu 22.04
# Note: docker compose is built-in
# Ref: https://docs.docker.com/engine/install/ubuntu/
---
- hosts: ubuntu
  collections:
    - community.docker
  become: true
  tasks:
  - name: Update package manager cache
    apt:
      update_cache: yes

  - name: Install required packages
    apt:
      name:
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
      state: present

  - name: Fetch Docker GPG key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
      keyring: /usr/share/keyrings/docker-archive-keyring.gpg

  - name: Grab arch
    shell: dpkg --print-architecture
    register: myarch

  - name: Grab lsb-release
    shell: lsb_release -cs
    register: myrelease

  - name: Add Docker APT repository
    ansible.builtin.apt_repository:
      # repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu jammy stable"
      repo: "deb [arch={{ myarch.stdout }} signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ myrelease.stdout }} stable"
      state: present

  - name: Update package manager cache again
    apt:
      update_cache: yes

  - name: Install Docker CE
    apt:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
      state: present

  - name: Enable Docker service
    service:
      name: docker
      enabled: yes

  - name: Enable containerd service
    service:
      name: containerd
      enabled: yes

  - name: Create 'docker' group
    group:
      name: docker
      state: present

  - name: Add current user to 'docker' group
    user:
      name: ubuntu
      groups: docker
      append: yes

  # - name: Change to 'docker' group
  #   shell: newgrp docker
  #   become: yes

  - name: Test Docker installation
    docker_container:
      name: hello-world
      image: hello-world
      state: present
      pull: true